# Generated by Django 5.2.1 on 2025-10-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='blog_videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='You can add images, videos, and YouTube links here'),
        ),
    ]
