# Generated by Django 5.2.1 on 2025-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_video_file_post_youtube_url_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to The Daily Learning', max_length=200)),
                ('hero_subtitle', models.TextField(default='Discover insights, tutorials, and knowledge across various topics', max_length=500)),
                ('about_section', models.TextField(default='We share quality content to help you learn and grow. Explore our categories and find what interests you.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
    ]
